#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pollenalarm.Droid.Resource", IsApplication=true)]

namespace Pollenalarm.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int pollenalarm_blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int pollenalarm_blue_dark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_default_margin = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ambrosia = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Ampfer = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Beifuss = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Birke = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Buche = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Eiche = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Erle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Graeser = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Hasel = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_accept = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_new = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_search = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_delete_white_24dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_lens_black_24dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_panorama_fish_eye_black_24dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Pappel = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Roggen = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Ulme = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Wegerich = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Weide = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090019
			public const int action_add_city = 2131296281;
			
			// aapt resource value: 0x7f090016
			public const int action_add_city_confirm = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int action_delete_city = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int action_edit_city = 2131296280;
			
			// aapt resource value: 0x7f090000
			public const int addEditCityName = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int addEditCityZip = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int cityListView = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int fragmentContainer = 2131296258;
			
			// aapt resource value: 0x7f090012
			public const int ivBackground = 2131296274;
			
			// aapt resource value: 0x7f090008
			public const int linearLayout1 = 2131296264;
			
			// aapt resource value: 0x7f09000a
			public const int linearLayout2 = 2131296266;
			
			// aapt resource value: 0x7f090003
			public const int pbLoading = 2131296259;
			
			// aapt resource value: 0x7f090010
			public const int pollenBloomTime = 2131296272;
			
			// aapt resource value: 0x7f09000e
			public const int pollenClinicalPollution = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int pollenDetailsBloomTimeTitle = 2131296271;
			
			// aapt resource value: 0x7f09000d
			public const int pollenDetailsClinicalPollutionTitle = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int pollenDetailsDescription = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int pollenDetailsDescriptionTitle = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int pollenDetailsImage = 2131296265;
			
			// aapt resource value: 0x7f090011
			public const int pollutionItem = 2131296273;
			
			// aapt resource value: 0x7f090015
			public const int pollutionListView = 2131296277;
			
			// aapt resource value: 0x7f090007
			public const int scrollView1 = 2131296263;
			
			// aapt resource value: 0x7f090004
			public const int textView1 = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int textView2 = 2131296261;
			
			// aapt resource value: 0x7f090013
			public const int tvName = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int tvPollution = 2131296276;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEditCity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int City = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Pollen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PollutionItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PollutionList = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int addeditcity_activity_actions = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int city_activity_actions = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int main_acticity_actions = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060004
			public const int action_add_city = 2131099652;
			
			// aapt resource value: 0x7f06001e
			public const int addEdit_error_body = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int addEdit_error_header = 2131099677;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int bloom_time = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int bloom_time_begin = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int bloom_time_end = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int bloom_time_middle = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int bloom_time_until = 2131099672;
			
			// aapt resource value: 0x7f060002
			public const int city_name = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int city_zip = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int clinical_pollution = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int clinical_pollution_high = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int clinical_pollution_intermediate = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int clinical_pollution_low = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int clinical_pollution_veryhigh = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int delete = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int delete_city_body = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int delete_city_title = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int edit = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int error_header = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int general_information = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int pollen_description = 2131099656;
			
			// aapt resource value: 0x7f060013
			public const int pollution_error_body = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int pollution_high = 2131099676;
			
			// aapt resource value: 0x7f06001a
			public const int pollution_low = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int pollution_medium = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int pollution_none = 2131099673;
			
			// aapt resource value: 0x7f060007
			public const int tab_aftertomorrow = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int tab_today = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int tab_tomorrow = 2131099654;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int PollenalarmActionBar = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int PollenalarmTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
