//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollenalarm.Frontend.Forms.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pollenalarm.Frontend.Forms.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        public static string NoPlacesWarning {
            get {
                return ResourceManager.GetString("NoPlacesWarning", resourceCulture);
            }
        }
        
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string GeoLocationFailedMessage {
            get {
                return ResourceManager.GetString("GeoLocationFailedMessage", resourceCulture);
            }
        }
        
        public static string GeoLocationFailedTitle {
            get {
                return ResourceManager.GetString("GeoLocationFailedTitle", resourceCulture);
            }
        }
        
        public static string InvalidEntriesMessage {
            get {
                return ResourceManager.GetString("InvalidEntriesMessage", resourceCulture);
            }
        }
        
        public static string InvalidEntriesTitle {
            get {
                return ResourceManager.GetString("InvalidEntriesTitle", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string LocationSettingsText {
            get {
                return ResourceManager.GetString("LocationSettingsText", resourceCulture);
            }
        }
        
        public static string NoPollutionWarningText {
            get {
                return ResourceManager.GetString("NoPollutionWarningText", resourceCulture);
            }
        }
        
        public static string PollutionNameLow {
            get {
                return ResourceManager.GetString("PollutionNameLow", resourceCulture);
            }
        }
        
        public static string PollutionNameMedium {
            get {
                return ResourceManager.GetString("PollutionNameMedium", resourceCulture);
            }
        }
        
        public static string PollutionNameNone {
            get {
                return ResourceManager.GetString("PollutionNameNone", resourceCulture);
            }
        }
        
        public static string PollutionNameStrong {
            get {
                return ResourceManager.GetString("PollutionNameStrong", resourceCulture);
            }
        }
        
        public static string PollutionNameVeryStrong {
            get {
                return ResourceManager.GetString("PollutionNameVeryStrong", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        public static string BloomTime {
            get {
                return ResourceManager.GetString("BloomTime", resourceCulture);
            }
        }
        
        public static string ClinicalPollution {
            get {
                return ResourceManager.GetString("ClinicalPollution", resourceCulture);
            }
        }
        
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        public static string PollenRelevant {
            get {
                return ResourceManager.GetString("PollenRelevant", resourceCulture);
            }
        }
        
        public static string PollenSelection {
            get {
                return ResourceManager.GetString("PollenSelection", resourceCulture);
            }
        }
        
        public static string SelectPollen {
            get {
                return ResourceManager.GetString("SelectPollen", resourceCulture);
            }
        }
        
        public static string SelectPollenText {
            get {
                return ResourceManager.GetString("SelectPollenText", resourceCulture);
            }
        }
        
        public static string ShowSelectedPollenOnlySettingsText {
            get {
                return ResourceManager.GetString("ShowSelectedPollenOnlySettingsText", resourceCulture);
            }
        }
        
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeletePlaceMessage {
            get {
                return ResourceManager.GetString("DeletePlaceMessage", resourceCulture);
            }
        }
        
        public static string DeletePlaceTitle {
            get {
                return ResourceManager.GetString("DeletePlaceTitle", resourceCulture);
            }
        }
        
        public static string LocationSettingsDetails {
            get {
                return ResourceManager.GetString("LocationSettingsDetails", resourceCulture);
            }
        }
        
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string GoodDay {
            get {
                return ResourceManager.GetString("GoodDay", resourceCulture);
            }
        }
        
        public static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        public static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        public static string GoodNight {
            get {
                return ResourceManager.GetString("GoodNight", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string SearchBarPlaceholder {
            get {
                return ResourceManager.GetString("SearchBarPlaceholder", resourceCulture);
            }
        }
        
        public static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        public static string BloomingGroupName {
            get {
                return ResourceManager.GetString("BloomingGroupName", resourceCulture);
            }
        }
        
        public static string NonBloomingGroupName {
            get {
                return ResourceManager.GetString("NonBloomingGroupName", resourceCulture);
            }
        }
    }
}
