//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pollenalarm.Frontend.Forms.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pollenalarm.Frontend.Forms.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollenalarm.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, something went wrong and we could not locate your current position. Please make sure, that your device has GPS and that it is turned on..
        /// </summary>
        public static string GeoLocationFailedMessage {
            get {
                return ResourceManager.GetString("GeoLocationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you?.
        /// </summary>
        public static string GeoLocationFailedTitle {
            get {
                return ResourceManager.GetString("GeoLocationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we could not validate your entries. Please check them and try again..
        /// </summary>
        public static string InvalidEntriesMessage {
            get {
                return ResourceManager.GetString("InvalidEntriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entries.
        /// </summary>
        public static string InvalidEntriesTitle {
            get {
                return ResourceManager.GetString("InvalidEntriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my current location.
        /// </summary>
        public static string LocationSettingsText {
            get {
                return ResourceManager.GetString("LocationSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s empty down here. Add your favorite places to keep an overview of their pollen pollution..
        /// </summary>
        public static string NoPlacesWarning {
            get {
                return ResourceManager.GetString("NoPlacesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find any pollution information for this place. Please check the zip code..
        /// </summary>
        public static string NoPollutionWarningText {
            get {
                return ResourceManager.GetString("NoPollutionWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string PollutionNameLow {
            get {
                return ResourceManager.GetString("PollutionNameLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string PollutionNameMedium {
            get {
                return ResourceManager.GetString("PollutionNameMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PollutionNameNone {
            get {
                return ResourceManager.GetString("PollutionNameNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        public static string PollutionNameStrong {
            get {
                return ResourceManager.GetString("PollutionNameStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very strong.
        /// </summary>
        public static string PollutionNameVeryStrong {
            get {
                return ResourceManager.GetString("PollutionNameVeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
